package com.cms.optimizer;

import java.util.Collection;
import java.util.LinkedList;
import java.util.List;

import com.alibaba.dubbo.common.serialize.support.SerializationOptimizer;
import com.alibaba.fastjson.JSONObject;
import com.cms.mapper.maoyi.GoodsService;
import com.cms.mapper.maoyi.StorageService;
import com.cms.model.Employee;
import com.cms.model.User;
import com.cms.model.dict.BaseIndustry;
import com.cms.model.dict.BaseProduct;
import com.cms.model.elasticsearch.cm.CmsProduceEs;
import com.cms.model.elasticsearch.cm.EnterpriseInfoEs;
import com.cms.model.elasticsearch.cm.PageEnterprise;
import com.cms.model.elasticsearch.cm.PageProduce;
import com.cms.model.manager.OrderDicBean;
import com.cms.model.manager.Tree;
import com.cms.model.manager.accessBean;
import com.cms.model.manager.accountBean;
import com.cms.model.manager.baseDicBean;
import com.cms.model.manager.carDicBean;
import com.cms.model.manager.comboBean;
import com.cms.model.manager.companyBean;
import com.cms.model.manager.dataRoleBean;
import com.cms.model.manager.departmentBean;
import com.cms.model.manager.driverBean;
import com.cms.model.manager.lineBean;
import com.cms.model.manager.loginUserBean;
import com.cms.model.manager.menuBean;
import com.cms.model.manager.messageLogBean;
import com.cms.model.manager.mileageBean;
import com.cms.model.manager.premiumBean;
import com.cms.model.manager.quoteBean;
import com.cms.model.manager.roleBean;
import com.cms.model.manager.stationBean;
import com.cms.model.manager.subCompanyBean;
import com.cms.model.manager.userBean;
import com.cms.model.manager.userGradeBean;
import com.cms.model.manager.userShortcutMenuBean;
import com.cms.model.manager.webRoleBean;
import com.cms.model.maoyi.CmsGoods;
import com.cms.model.maoyi.CmsProduct;
import com.cms.model.maoyi.EnterpriseInfo;
import com.cms.model.maoyi.EnterpriseQualification;
import com.cms.model.maoyi.EnterpriseToOutBean;
import com.cms.model.maoyi.NetworkBean;
import com.cms.model.shengchang.CompAttachRel;
import com.cms.model.shengchang.CompBaseInfo;
import com.cms.model.shengchang.CompBuyRule;
import com.cms.model.shengchang.CompBuyRuleArea;
import com.cms.model.shengchang.CompContactInfo;
import com.cms.model.shengchang.CompMainProArea;
import com.cms.model.shengchang.CompSaleRule;
import com.cms.model.shengchang.CompSaleRuleArea;
import com.cms.model.shengchang.DocOutBean;
import com.cms.model.shengchang.MainDocBean;
import com.cms.model.shengchang.MainProductBean;
import com.cms.model.shengchang.MainProductOutBean;
import com.cms.model.shengchang.ProductBean;
import com.cms.model.shengchang.ProductDocBean;
import com.cms.model.shengchang.ProductOutBean;
import com.cms.model.shengchang.ProductParameterBean;
import com.cms.model.shengchang.ProductPriceBean;
import com.cms.model.shengchang.ProductSellRuleAreaBean;
import com.cms.model.shengchang.ProductSellRuleBean;
import com.cms.model.shengchang.ProductSellRuleOutBean;
import com.cms.model.shengchang.*;
import com.cms.model.userCenter.SysUser;
import com.cms.model.userCenter.SysUserEnterpriseAptitude;
import com.cms.model.userCenter.SysUserEnterpriseAuth;
import com.cms.model.userCenter.SysUserEnterpriseInfo;
import com.cms.model.userCenter.SysUserGoodsAddress;
import com.cms.model.userCenter.SysUserSingelInfo;
import com.cms.model.userCenter.SysUserTradeAccout;
import com.cms.model.userCenter.SysUserTradeInfo;
import com.cms.model.util.GlobalConstant;
import com.cms.model.util.Grid;
import com.cms.model.util.PageFilter;
import com.cms.model.util.SessionInfo;
import com.cms.model.wuliu.AreaBean;
import com.cms.model.wuliu.CarBean;
import com.cms.model.wuliu.CarOnlineBean;
import com.cms.model.wuliu.CheyuanBean;
import com.cms.model.wuliu.ChppQueryParam;
import com.cms.model.wuliu.CityBean;
import com.cms.model.wuliu.DicBean;
import com.cms.model.wuliu.HuoyuanBean;
import com.cms.model.wuliu.MyCarBean;
import com.cms.model.wuliu.ProvinceBean;
import com.cms.model.wuliu.Test;
import com.cms.model.wuliu.VaServiceBean;

public class SerializationOptimizerImpl implements SerializationOptimizer {
	
	    public Collection<Class> getSerializableClasses() {
	        List<Class> classes = new LinkedList<Class>();
	      
            classes.add(User.class);
            classes.add(Employee.class);
            classes.add(AreaBean.class);
            classes.add(CarBean.class);
            classes.add(CarOnlineBean.class);
            classes.add(CheyuanBean.class);
            classes.add(CityBean.class);
            classes.add(HuoyuanBean.class);
            classes.add(OrderDicBean.class);
            classes.add(ProvinceBean.class);
            classes.add(VaServiceBean.class);
            classes.add(Grid.class);
            classes.add(PageFilter.class);
            classes.add(SessionInfo.class);
            classes.add(MyCarBean.class);
            classes.add(Test.class);
            classes.add(GlobalConstant.class);
            classes.add(accessBean.class);
            classes.add(accountBean.class);
            classes.add(baseDicBean.class);
            classes.add(carDicBean.class);
            classes.add(comboBean.class);
            classes.add(companyBean.class);
            classes.add(dataRoleBean.class);
            classes.add(departmentBean.class);
            classes.add(driverBean.class);
            classes.add(lineBean.class);
            classes.add(loginUserBean.class);
            classes.add(menuBean.class);
            classes.add(messageLogBean.class);
            classes.add(mileageBean.class);
            classes.add(OrderDicBean.class);
            classes.add(premiumBean.class);
            classes.add(quoteBean.class);
            classes.add(roleBean.class);
            classes.add(stationBean.class);
            classes.add(subCompanyBean.class);
            classes.add(Tree.class);
            classes.add(userBean.class);
            classes.add(userGradeBean.class);
            classes.add(userShortcutMenuBean.class);
            classes.add(webRoleBean.class);
            classes.add(JSONObject.class);
            classes.add(SysUser.class);
            classes.add(SysUserEnterpriseAptitude.class);
            classes.add(SysUserEnterpriseAuth.class);
            classes.add(SysUserEnterpriseInfo.class);
            classes.add(SysUserGoodsAddress.class);
            classes.add(SysUserSingelInfo.class);
            classes.add(SysUserTradeAccout.class);
            classes.add(SysUserTradeInfo.class);
            classes.add(ChppQueryParam.class);
            classes.add(DicBean.class);
            classes.add(BaseProduct.class);
            classes.add(BaseIndustry.class);
            
            classes.add(CompBaseInfo.class);
            classes.add(CompAttachRel.class);
            classes.add(CompContactInfo.class);
            
            
            classes.add(CompBuyRule.class);
            classes.add(CompBuyRuleArea.class);
            classes.add(CompSaleRule.class);
            classes.add(CompSaleRuleArea.class);
            classes.add(CompMainProArea.class);
            

            classes.add(MainProductBean.class);
            classes.add(MainDocBean.class);
            classes.add(ProductBean.class);
            classes.add(ProductDocBean.class);
            classes.add(ProductSellRuleBean.class);
            classes.add(ProductSellRuleAreaBean.class);
            classes.add(ProductPriceBean.class);
            classes.add(ProductParameterBean.class);
            classes.add(ProductSellRuleOutBean.class);
            classes.add(MainProductOutBean.class);
            classes.add(ProductOutBean.class);
            classes.add(DocOutBean.class);
            classes.add(EnterpriseInfoEs.class);
            classes.add(CmsProduceEs.class);
            classes.add(PageProduce.class);
            classes.add(CmsGoods.class);
            classes.add(CmsProduct.class);
            classes.add(EnterpriseToOutBean.class);
            classes.add(EnterpriseInfo.class);
            classes.add(EnterpriseQualification.class);
            classes.add(NetworkBean.class);
            classes.add(GoodsService.class);
            classes.add(StorageService.class);
            classes.add(PageEnterprise.class);
            classes.add(PurchaseTenderOrder.class);
            classes.add(PurchaseTenderDoc.class);
            classes.add(PurchaseTenderArea.class);
            classes.add(PurchaseTenderDetail.class);
            classes.add(PurchaseTenderDetailDoc.class);
            classes.add(PurchaseTenderOrderSupplier.class);
            classes.add(SaleBidOrder.class);
            classes.add(SaleBidOrderDetail.class);
            classes.add(PurchaseTenderOrderOut.class);
            classes.add(PurchaseTenderAreaOut.class);
            classes.add(PurchaseTenderOrderSupplierOut.class);
            classes.add(PurchaseTenderDetailOut.class);
            classes.add(PurchaseTenderDetailDocOut.class);
	       return classes;
	   }
}