package com.cms.mapper.shengchan;

import java.util.List;

import com.alibaba.fastjson.JSONObject;
import com.cms.model.shengchang.CompSuppliers;

public interface CompSuppliersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_suppliers
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_suppliers
	 * @mbggenerated
	 */
	int insert(CompSuppliers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_suppliers
	 * @mbggenerated
	 */
	int insertSelective(CompSuppliers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_suppliers
	 * @mbggenerated
	 */
	CompSuppliers selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_suppliers
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CompSuppliers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_suppliers
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CompSuppliers record);
	

	List getAllSupplierIdByCompId(JSONObject obj);

	CompSuppliers getCompSuppliers(JSONObject obj);

	List<CompSuppliers> getEnterpriseInfo(JSONObject obj);

	int getTotalSupplierMaoyi(JSONObject obj);
}