package com.cms.mapper.shengchan;

import com.cms.model.shengchang.CompBuyRuleArea;

import java.util.List;

public interface CompBuyRuleAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_buy_rule_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_buy_rule_area
     *
     * @mbggenerated
     */
    int insert(CompBuyRuleArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_buy_rule_area
     *
     * @mbggenerated
     */
    int insertSelective(CompBuyRuleArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_buy_rule_area
     *
     * @mbggenerated
     */
    CompBuyRuleArea selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_buy_rule_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompBuyRuleArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_buy_rule_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompBuyRuleArea record);
    
    
    List<CompBuyRuleArea> getBuyAreaByRuleId(Long ruleId);

	void deleteBuyRuleByRuleId(Long buyId);
}