package com.cms.mapper.shengchan;

import com.cms.model.shengchang.CompSaleRule;

import java.util.List;

public interface CompSaleRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_sale_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_sale_rule
     *
     * @mbggenerated
     */
    int insert(CompSaleRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_sale_rule
     *
     * @mbggenerated
     */
    int insertSelective(CompSaleRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_sale_rule
     *
     * @mbggenerated
     */
    CompSaleRule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_sale_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompSaleRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_sale_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompSaleRule record);
    
    List<CompSaleRule> getAllSaleRule();
    
    public List<CompSaleRule> getSaleRuleByCompId(Long compid);
    
    public List<CompSaleRule> getSaleRuleByCond(CompSaleRule rule);
}