package com.cms.mapper.shengchan;

import com.cms.model.shengchang.CompAttachRel;

import java.util.List;

public interface CompAttachRelMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_attach_rel
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_attach_rel
	 * @mbggenerated
	 */
	int insert(CompAttachRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_attach_rel
	 * @mbggenerated
	 */
	int insertSelective(CompAttachRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_attach_rel
	 * @mbggenerated
	 */
	CompAttachRel selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_attach_rel
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CompAttachRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_attach_rel
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CompAttachRel record);

	List selectByCompId(long compId);
	
	int updateAttach(CompAttachRel record);
	
	
	void delByCompIdAndType(String compid,String relType);
	
	
	public List<CompAttachRel> getAttachByCompidAndType(CompAttachRel rel);

}