package com.cms.mapper.shengchan;

import com.alibaba.fastjson.JSONObject;
import com.cms.model.shengchang.CompBaseInfo;

import java.util.List;

public interface CompBaseInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company_base_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long compid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company_base_info
	 * @mbggenerated
	 */
	int insert(CompBaseInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company_base_info
	 * @mbggenerated
	 */
	int insertSelective(CompBaseInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company_base_info
	 * @mbggenerated
	 */
	CompBaseInfo selectByPrimaryKey(Long compid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company_base_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CompBaseInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company_base_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CompBaseInfo record);

	List getAllCompany();
	
	int updateBaseInfo(CompBaseInfo compBaseInfo);
	
	int updateJiagong(CompBaseInfo compBaseInfo);
	
	List pageSupplier(JSONObject obj);

	int getSupplierTotal(JSONObject obj);
	
}