package com.cms.mapper.shengchan;

import com.cms.model.shengchang.CompContactInfo;

import java.util.List;

public interface CompContactInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_contact_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_contact_info
	 * @mbggenerated
	 */
	int insert(CompContactInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_contact_info
	 * @mbggenerated
	 */
	int insertSelective(CompContactInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_contact_info
	 * @mbggenerated
	 */
	CompContactInfo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_contact_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CompContactInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_contact_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CompContactInfo record);

	List selectByCompId(long compId);
}