package com.cms.mapper.shengchan;

import com.alibaba.fastjson.JSONObject;
import com.cms.model.shengchang.CompBuyRule;

import java.util.List;
import java.util.Map;

public interface CompBuyRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_buy_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_buy_rule
     *
     * @mbggenerated
     */
    int insert(CompBuyRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_buy_rule
     *
     * @mbggenerated
     */
    int insertSelective(CompBuyRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_buy_rule
     *
     * @mbggenerated
     */
    CompBuyRule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_buy_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompBuyRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comp_buy_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompBuyRule record);
    
    
    List<CompBuyRule> getAllBuyRule();
    
    List<CompBuyRule> getBuyRuleByCompId(Long compId);

	List<CompBuyRule> pageBuyRule(JSONObject obj);
	
	int getTotalBuyRule(CompBuyRule compBuyRule);

    Map getBuyRuleAreaMap(CompBuyRule compBuyRule);
}