package com.cms.mapper.shengchan;

import com.cms.model.shengchang.CompSaleRuleArea;

import java.util.List;

public interface CompSaleRuleAreaMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_sale_rule_area
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_sale_rule_area
	 * @mbggenerated
	 */
	int insert(CompSaleRuleArea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_sale_rule_area
	 * @mbggenerated
	 */
	int insertSelective(CompSaleRuleArea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_sale_rule_area
	 * @mbggenerated
	 */
	CompSaleRuleArea selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_sale_rule_area
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CompSaleRuleArea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_sale_rule_area
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CompSaleRuleArea record);

	List<CompSaleRuleArea> getSaleAreaByRuleId(Long ruleId);
    
    void delRuleBySaleId(Long saleId);
    
    
    
	
}