package com.cms.mapper.shengchan;

import java.util.List;

import com.cms.model.shengchang.StorageTransportDemand;

public interface StorageTransportDemandMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_transport_demand
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_transport_demand
	 * @mbggenerated
	 */
	int insert(StorageTransportDemand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_transport_demand
	 * @mbggenerated
	 */
	int insertSelective(StorageTransportDemand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_transport_demand
	 * @mbggenerated
	 */
	StorageTransportDemand selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_transport_demand
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(StorageTransportDemand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_transport_demand
	 * @mbggenerated
	 */
	int updateByPrimaryKey(StorageTransportDemand record);

	List<StorageTransportDemand> getAllStorageTransportDemand(String compid);
}