package com.cms.model.xiaofei.logon;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CmsXSysUser implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.uname
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.cert_type
     *
     * @mbggenerated
     */
    private String certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.cert_num
     *
     * @mbggenerated
     */
    private String certNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.user_type
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.member_type
     *
     * @mbggenerated
     */
    private String memberType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.member_other_mark
     *
     * @mbggenerated
     */
    private String memberOtherMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.pwd_protect_1
     *
     * @mbggenerated
     */
    private String pwdProtect1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.pwd_protect_2
     *
     * @mbggenerated
     */
    private String pwdProtect2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.pwd_protect_3
     *
     * @mbggenerated
     */
    private String pwdProtect3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.pwd_protect_answer_1
     *
     * @mbggenerated
     */
    private String pwdProtectAnswer1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.pwd_protect_answer_2
     *
     * @mbggenerated
     */
    private String pwdProtectAnswer2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.pwd_protect_answer_3
     *
     * @mbggenerated
     */
    private String pwdProtectAnswer3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.company_address_province
     *
     * @mbggenerated
     */
    private String companyAddressProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.company_address_city
     *
     * @mbggenerated
     */
    private String companyAddressCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.company_address_county
     *
     * @mbggenerated
     */
    private String companyAddressCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.company_address_detail
     *
     * @mbggenerated
     */
    private String companyAddressDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.contact_person_name
     *
     * @mbggenerated
     */
    private String contactPersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.contact_person_sex
     *
     * @mbggenerated
     */
    private String contactPersonSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.contact_person_phone
     *
     * @mbggenerated
     */
    private String contactPersonPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.contact_person_depart
     *
     * @mbggenerated
     */
    private String contactPersonDepart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.contact_person_position
     *
     * @mbggenerated
     */
    private String contactPersonPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.contact_person_tel
     *
     * @mbggenerated
     */
    private String contactPersonTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.contact_person_certType
     *
     * @mbggenerated
     */
    private String contactPersonCerttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.contact_person_certNum
     *
     * @mbggenerated
     */
    private String contactPersonCertnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.user_number
     *
     * @mbggenerated
     */
    private String userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.entry_date
     *
     * @mbggenerated
     */
    private String entryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.creator_time
     *
     * @mbggenerated
     */
    private String creatorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.is_enable
     *
     * @mbggenerated
     */
    private String isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.is_default
     *
     * @mbggenerated
     */
    private String isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.depart_id
     *
     * @mbggenerated
     */
    private String departId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.company_id
     *
     * @mbggenerated
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.subcompany_id
     *
     * @mbggenerated
     */
    private String subcompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.station_id
     *
     * @mbggenerated
     */
    private String stationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.pay_pwd
     *
     * @mbggenerated
     */
    private String payPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.is_authenticate
     *
     * @mbggenerated
     */
    private String isAuthenticate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.postcode
     *
     * @mbggenerated
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_x_sys_user.visible_status
     *
     * @mbggenerated
     */
    private String visibleStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.uid
     *
     * @return the value of cms_x_sys_user.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.uid
     *
     * @param uid the value for cms_x_sys_user.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.parent_id
     *
     * @return the value of cms_x_sys_user.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.parent_id
     *
     * @param parentId the value for cms_x_sys_user.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.uname
     *
     * @return the value of cms_x_sys_user.uname
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.uname
     *
     * @param uname the value for cms_x_sys_user.uname
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.password
     *
     * @return the value of cms_x_sys_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.password
     *
     * @param password the value for cms_x_sys_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.phone
     *
     * @return the value of cms_x_sys_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.phone
     *
     * @param phone the value for cms_x_sys_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.realname
     *
     * @return the value of cms_x_sys_user.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.realname
     *
     * @param realname the value for cms_x_sys_user.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.sex
     *
     * @return the value of cms_x_sys_user.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.sex
     *
     * @param sex the value for cms_x_sys_user.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.tel
     *
     * @return the value of cms_x_sys_user.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.tel
     *
     * @param tel the value for cms_x_sys_user.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.cert_type
     *
     * @return the value of cms_x_sys_user.cert_type
     *
     * @mbggenerated
     */
    public String getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.cert_type
     *
     * @param certType the value for cms_x_sys_user.cert_type
     *
     * @mbggenerated
     */
    public void setCertType(String certType) {
        this.certType = certType == null ? null : certType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.cert_num
     *
     * @return the value of cms_x_sys_user.cert_num
     *
     * @mbggenerated
     */
    public String getCertNum() {
        return certNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.cert_num
     *
     * @param certNum the value for cms_x_sys_user.cert_num
     *
     * @mbggenerated
     */
    public void setCertNum(String certNum) {
        this.certNum = certNum == null ? null : certNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.email
     *
     * @return the value of cms_x_sys_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.email
     *
     * @param email the value for cms_x_sys_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.user_type
     *
     * @return the value of cms_x_sys_user.user_type
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.user_type
     *
     * @param userType the value for cms_x_sys_user.user_type
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.member_type
     *
     * @return the value of cms_x_sys_user.member_type
     *
     * @mbggenerated
     */
    public String getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.member_type
     *
     * @param memberType the value for cms_x_sys_user.member_type
     *
     * @mbggenerated
     */
    public void setMemberType(String memberType) {
        this.memberType = memberType == null ? null : memberType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.member_other_mark
     *
     * @return the value of cms_x_sys_user.member_other_mark
     *
     * @mbggenerated
     */
    public String getMemberOtherMark() {
        return memberOtherMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.member_other_mark
     *
     * @param memberOtherMark the value for cms_x_sys_user.member_other_mark
     *
     * @mbggenerated
     */
    public void setMemberOtherMark(String memberOtherMark) {
        this.memberOtherMark = memberOtherMark == null ? null : memberOtherMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.pwd_protect_1
     *
     * @return the value of cms_x_sys_user.pwd_protect_1
     *
     * @mbggenerated
     */
    public String getPwdProtect1() {
        return pwdProtect1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.pwd_protect_1
     *
     * @param pwdProtect1 the value for cms_x_sys_user.pwd_protect_1
     *
     * @mbggenerated
     */
    public void setPwdProtect1(String pwdProtect1) {
        this.pwdProtect1 = pwdProtect1 == null ? null : pwdProtect1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.pwd_protect_2
     *
     * @return the value of cms_x_sys_user.pwd_protect_2
     *
     * @mbggenerated
     */
    public String getPwdProtect2() {
        return pwdProtect2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.pwd_protect_2
     *
     * @param pwdProtect2 the value for cms_x_sys_user.pwd_protect_2
     *
     * @mbggenerated
     */
    public void setPwdProtect2(String pwdProtect2) {
        this.pwdProtect2 = pwdProtect2 == null ? null : pwdProtect2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.pwd_protect_3
     *
     * @return the value of cms_x_sys_user.pwd_protect_3
     *
     * @mbggenerated
     */
    public String getPwdProtect3() {
        return pwdProtect3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.pwd_protect_3
     *
     * @param pwdProtect3 the value for cms_x_sys_user.pwd_protect_3
     *
     * @mbggenerated
     */
    public void setPwdProtect3(String pwdProtect3) {
        this.pwdProtect3 = pwdProtect3 == null ? null : pwdProtect3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.pwd_protect_answer_1
     *
     * @return the value of cms_x_sys_user.pwd_protect_answer_1
     *
     * @mbggenerated
     */
    public String getPwdProtectAnswer1() {
        return pwdProtectAnswer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.pwd_protect_answer_1
     *
     * @param pwdProtectAnswer1 the value for cms_x_sys_user.pwd_protect_answer_1
     *
     * @mbggenerated
     */
    public void setPwdProtectAnswer1(String pwdProtectAnswer1) {
        this.pwdProtectAnswer1 = pwdProtectAnswer1 == null ? null : pwdProtectAnswer1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.pwd_protect_answer_2
     *
     * @return the value of cms_x_sys_user.pwd_protect_answer_2
     *
     * @mbggenerated
     */
    public String getPwdProtectAnswer2() {
        return pwdProtectAnswer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.pwd_protect_answer_2
     *
     * @param pwdProtectAnswer2 the value for cms_x_sys_user.pwd_protect_answer_2
     *
     * @mbggenerated
     */
    public void setPwdProtectAnswer2(String pwdProtectAnswer2) {
        this.pwdProtectAnswer2 = pwdProtectAnswer2 == null ? null : pwdProtectAnswer2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.pwd_protect_answer_3
     *
     * @return the value of cms_x_sys_user.pwd_protect_answer_3
     *
     * @mbggenerated
     */
    public String getPwdProtectAnswer3() {
        return pwdProtectAnswer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.pwd_protect_answer_3
     *
     * @param pwdProtectAnswer3 the value for cms_x_sys_user.pwd_protect_answer_3
     *
     * @mbggenerated
     */
    public void setPwdProtectAnswer3(String pwdProtectAnswer3) {
        this.pwdProtectAnswer3 = pwdProtectAnswer3 == null ? null : pwdProtectAnswer3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.company_name
     *
     * @return the value of cms_x_sys_user.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.company_name
     *
     * @param companyName the value for cms_x_sys_user.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.company_address_province
     *
     * @return the value of cms_x_sys_user.company_address_province
     *
     * @mbggenerated
     */
    public String getCompanyAddressProvince() {
        return companyAddressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.company_address_province
     *
     * @param companyAddressProvince the value for cms_x_sys_user.company_address_province
     *
     * @mbggenerated
     */
    public void setCompanyAddressProvince(String companyAddressProvince) {
        this.companyAddressProvince = companyAddressProvince == null ? null : companyAddressProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.company_address_city
     *
     * @return the value of cms_x_sys_user.company_address_city
     *
     * @mbggenerated
     */
    public String getCompanyAddressCity() {
        return companyAddressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.company_address_city
     *
     * @param companyAddressCity the value for cms_x_sys_user.company_address_city
     *
     * @mbggenerated
     */
    public void setCompanyAddressCity(String companyAddressCity) {
        this.companyAddressCity = companyAddressCity == null ? null : companyAddressCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.company_address_county
     *
     * @return the value of cms_x_sys_user.company_address_county
     *
     * @mbggenerated
     */
    public String getCompanyAddressCounty() {
        return companyAddressCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.company_address_county
     *
     * @param companyAddressCounty the value for cms_x_sys_user.company_address_county
     *
     * @mbggenerated
     */
    public void setCompanyAddressCounty(String companyAddressCounty) {
        this.companyAddressCounty = companyAddressCounty == null ? null : companyAddressCounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.company_address_detail
     *
     * @return the value of cms_x_sys_user.company_address_detail
     *
     * @mbggenerated
     */
    public String getCompanyAddressDetail() {
        return companyAddressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.company_address_detail
     *
     * @param companyAddressDetail the value for cms_x_sys_user.company_address_detail
     *
     * @mbggenerated
     */
    public void setCompanyAddressDetail(String companyAddressDetail) {
        this.companyAddressDetail = companyAddressDetail == null ? null : companyAddressDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.contact_person_name
     *
     * @return the value of cms_x_sys_user.contact_person_name
     *
     * @mbggenerated
     */
    public String getContactPersonName() {
        return contactPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.contact_person_name
     *
     * @param contactPersonName the value for cms_x_sys_user.contact_person_name
     *
     * @mbggenerated
     */
    public void setContactPersonName(String contactPersonName) {
        this.contactPersonName = contactPersonName == null ? null : contactPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.contact_person_sex
     *
     * @return the value of cms_x_sys_user.contact_person_sex
     *
     * @mbggenerated
     */
    public String getContactPersonSex() {
        return contactPersonSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.contact_person_sex
     *
     * @param contactPersonSex the value for cms_x_sys_user.contact_person_sex
     *
     * @mbggenerated
     */
    public void setContactPersonSex(String contactPersonSex) {
        this.contactPersonSex = contactPersonSex == null ? null : contactPersonSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.contact_person_phone
     *
     * @return the value of cms_x_sys_user.contact_person_phone
     *
     * @mbggenerated
     */
    public String getContactPersonPhone() {
        return contactPersonPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.contact_person_phone
     *
     * @param contactPersonPhone the value for cms_x_sys_user.contact_person_phone
     *
     * @mbggenerated
     */
    public void setContactPersonPhone(String contactPersonPhone) {
        this.contactPersonPhone = contactPersonPhone == null ? null : contactPersonPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.contact_person_depart
     *
     * @return the value of cms_x_sys_user.contact_person_depart
     *
     * @mbggenerated
     */
    public String getContactPersonDepart() {
        return contactPersonDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.contact_person_depart
     *
     * @param contactPersonDepart the value for cms_x_sys_user.contact_person_depart
     *
     * @mbggenerated
     */
    public void setContactPersonDepart(String contactPersonDepart) {
        this.contactPersonDepart = contactPersonDepart == null ? null : contactPersonDepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.contact_person_position
     *
     * @return the value of cms_x_sys_user.contact_person_position
     *
     * @mbggenerated
     */
    public String getContactPersonPosition() {
        return contactPersonPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.contact_person_position
     *
     * @param contactPersonPosition the value for cms_x_sys_user.contact_person_position
     *
     * @mbggenerated
     */
    public void setContactPersonPosition(String contactPersonPosition) {
        this.contactPersonPosition = contactPersonPosition == null ? null : contactPersonPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.contact_person_tel
     *
     * @return the value of cms_x_sys_user.contact_person_tel
     *
     * @mbggenerated
     */
    public String getContactPersonTel() {
        return contactPersonTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.contact_person_tel
     *
     * @param contactPersonTel the value for cms_x_sys_user.contact_person_tel
     *
     * @mbggenerated
     */
    public void setContactPersonTel(String contactPersonTel) {
        this.contactPersonTel = contactPersonTel == null ? null : contactPersonTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.contact_person_certType
     *
     * @return the value of cms_x_sys_user.contact_person_certType
     *
     * @mbggenerated
     */
    public String getContactPersonCerttype() {
        return contactPersonCerttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.contact_person_certType
     *
     * @param contactPersonCerttype the value for cms_x_sys_user.contact_person_certType
     *
     * @mbggenerated
     */
    public void setContactPersonCerttype(String contactPersonCerttype) {
        this.contactPersonCerttype = contactPersonCerttype == null ? null : contactPersonCerttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.contact_person_certNum
     *
     * @return the value of cms_x_sys_user.contact_person_certNum
     *
     * @mbggenerated
     */
    public String getContactPersonCertnum() {
        return contactPersonCertnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.contact_person_certNum
     *
     * @param contactPersonCertnum the value for cms_x_sys_user.contact_person_certNum
     *
     * @mbggenerated
     */
    public void setContactPersonCertnum(String contactPersonCertnum) {
        this.contactPersonCertnum = contactPersonCertnum == null ? null : contactPersonCertnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.user_number
     *
     * @return the value of cms_x_sys_user.user_number
     *
     * @mbggenerated
     */
    public String getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.user_number
     *
     * @param userNumber the value for cms_x_sys_user.user_number
     *
     * @mbggenerated
     */
    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber == null ? null : userNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.position
     *
     * @return the value of cms_x_sys_user.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.position
     *
     * @param position the value for cms_x_sys_user.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.entry_date
     *
     * @return the value of cms_x_sys_user.entry_date
     *
     * @mbggenerated
     */
    public String getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.entry_date
     *
     * @param entryDate the value for cms_x_sys_user.entry_date
     *
     * @mbggenerated
     */
    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.creator_time
     *
     * @return the value of cms_x_sys_user.creator_time
     *
     * @mbggenerated
     */
    public String getCreatorTime() {
        return creatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.creator_time
     *
     * @param creatorTime the value for cms_x_sys_user.creator_time
     *
     * @mbggenerated
     */
    public void setCreatorTime(String creatorTime) {
        this.creatorTime = creatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.creator
     *
     * @return the value of cms_x_sys_user.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.creator
     *
     * @param creator the value for cms_x_sys_user.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.status
     *
     * @return the value of cms_x_sys_user.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.status
     *
     * @param status the value for cms_x_sys_user.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.is_enable
     *
     * @return the value of cms_x_sys_user.is_enable
     *
     * @mbggenerated
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.is_enable
     *
     * @param isEnable the value for cms_x_sys_user.is_enable
     *
     * @mbggenerated
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable == null ? null : isEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.is_default
     *
     * @return the value of cms_x_sys_user.is_default
     *
     * @mbggenerated
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.is_default
     *
     * @param isDefault the value for cms_x_sys_user.is_default
     *
     * @mbggenerated
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault == null ? null : isDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.description
     *
     * @return the value of cms_x_sys_user.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.description
     *
     * @param description the value for cms_x_sys_user.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.depart_id
     *
     * @return the value of cms_x_sys_user.depart_id
     *
     * @mbggenerated
     */
    public String getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.depart_id
     *
     * @param departId the value for cms_x_sys_user.depart_id
     *
     * @mbggenerated
     */
    public void setDepartId(String departId) {
        this.departId = departId == null ? null : departId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.company_id
     *
     * @return the value of cms_x_sys_user.company_id
     *
     * @mbggenerated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.company_id
     *
     * @param companyId the value for cms_x_sys_user.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.subcompany_id
     *
     * @return the value of cms_x_sys_user.subcompany_id
     *
     * @mbggenerated
     */
    public String getSubcompanyId() {
        return subcompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.subcompany_id
     *
     * @param subcompanyId the value for cms_x_sys_user.subcompany_id
     *
     * @mbggenerated
     */
    public void setSubcompanyId(String subcompanyId) {
        this.subcompanyId = subcompanyId == null ? null : subcompanyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.station_id
     *
     * @return the value of cms_x_sys_user.station_id
     *
     * @mbggenerated
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.station_id
     *
     * @param stationId the value for cms_x_sys_user.station_id
     *
     * @mbggenerated
     */
    public void setStationId(String stationId) {
        this.stationId = stationId == null ? null : stationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.pay_pwd
     *
     * @return the value of cms_x_sys_user.pay_pwd
     *
     * @mbggenerated
     */
    public String getPayPwd() {
        return payPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.pay_pwd
     *
     * @param payPwd the value for cms_x_sys_user.pay_pwd
     *
     * @mbggenerated
     */
    public void setPayPwd(String payPwd) {
        this.payPwd = payPwd == null ? null : payPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.is_authenticate
     *
     * @return the value of cms_x_sys_user.is_authenticate
     *
     * @mbggenerated
     */
    public String getIsAuthenticate() {
        return isAuthenticate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.is_authenticate
     *
     * @param isAuthenticate the value for cms_x_sys_user.is_authenticate
     *
     * @mbggenerated
     */
    public void setIsAuthenticate(String isAuthenticate) {
        this.isAuthenticate = isAuthenticate == null ? null : isAuthenticate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.fax
     *
     * @return the value of cms_x_sys_user.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.fax
     *
     * @param fax the value for cms_x_sys_user.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.postcode
     *
     * @return the value of cms_x_sys_user.postcode
     *
     * @mbggenerated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.postcode
     *
     * @param postcode the value for cms_x_sys_user.postcode
     *
     * @mbggenerated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_x_sys_user.visible_status
     *
     * @return the value of cms_x_sys_user.visible_status
     *
     * @mbggenerated
     */
    public String getVisibleStatus() {
        return visibleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_x_sys_user.visible_status
     *
     * @param visibleStatus the value for cms_x_sys_user.visible_status
     *
     * @mbggenerated
     */
    public void setVisibleStatus(String visibleStatus) {
        this.visibleStatus = visibleStatus == null ? null : visibleStatus.trim();
    }
}