document.writeln("<div class=\"cmaosc_top\">");
document.writeln("    <div class=\"cmao_head\">");
document.writeln("    <span class=\"cmaosc_logo\"><a href=\"../index.html\" target=\"_self\"> <img src=\"../images/shenchans/logo_bai_img.png\"></a></span>");
document.writeln("        <a href=\"../index_sc.html\" target=\"_self\"><span class=\"cmaosc_pt\">生产应用平台</span></a>");
document.writeln("    </div>");
document.writeln("    <div class=\"cmaosc_tr\">");
document.writeln("");
document.writeln("        <span class=\"cmao_cmeu\">");
document.writeln("        <a href=\"#\"  data-toggle=\"dropdown\" aria-haspopup=\"true\"");
document.writeln("           aria-expanded=\"false\">");
document.writeln("          ");
document.writeln("            <i class=\"fa fa-caret-down\"></i>");
document.writeln("        </a>");
document.writeln("            <ul id=\"menu1\" class=\"dropdown-menu wei\" role=\"menu\" >");
document.writeln("                <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"javascript:void(0);\" target=\"_self\">帐户设置</a></li>");
document.writeln("                <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"javascript:void(0);\" target=\"_self\">客户管理</a></li>");
document.writeln("                <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"javascript:void(0);\">退出</a></li>");
document.writeln("            </ul>");
document.writeln("");
document.writeln("        </span>");
document.writeln("        <span class=\"cmao_tou\"><img src=\"../images/tou.png\" />   </span>");
document.writeln("        <span class=\"cmao_xi\">");
document.writeln("            <img src=\"../images/lingdang.png\" >");
document.writeln("               <img src=\"../images/chilun.png\" >");
document.writeln("        </span>");
document.writeln("        <span class=\"cmao_sc\">");
document.writeln("            我是生产商");
document.writeln("            <a href=\"#\"  data-toggle=\"dropdown\" aria-haspopup=\"true\"");
document.writeln("               aria-expanded=\"false\">");
document.writeln("");
document.writeln("                <i class=\"fa fa-caret-down\"></i>");
document.writeln("            </a>");
document.writeln("            <ul id=\"menu1\" class=\"dropdown-menu wei_f\" role=\"menu\" >");
document.writeln("                <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"javascript:void(0);\" target=\"_self\">我是经销商</a></li>");
document.writeln("                <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"javascript:void(0);\" target=\"_self\">我是物流商</a></li>");
document.writeln("                <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"javascript:void(0);\">退出</a></li>");
document.writeln("            </ul>");
document.writeln("        </span>");
document.writeln("        <span class=\"cmaosc_sou\"><input type=\"text\"  placeholder=\"请输入你需要的帮助\"  /><img src=\"../images/shenchans/fangda.jpg\" ></span>");
document.writeln("             <span class=\"cmaosc_bang\">");
document.writeln("            <div class=\"cmao_b\">");
document.writeln("                <p class=\"cmao_set\">帮助</p>");
document.writeln("                <ul class=\"camo_bs\">");
document.writeln("                    <li>联系</li>");
document.writeln("                    <li>上一级</li>");
document.writeln("                    <li>下一级</li>");
document.writeln("                    <li>退出</li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </span>");
document.writeln("    </div>");
document.writeln("");
document.writeln("</div>");