package com.cms.mapper.maoyi;

import com.cms.model.maoyi.FactoryDispatchOrder;

public interface FactoryDispatchOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory_dispatch_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String serviceOrderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory_dispatch_order
     *
     * @mbggenerated
     */
    int insert(FactoryDispatchOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory_dispatch_order
     *
     * @mbggenerated
     */
    int insertSelective(FactoryDispatchOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory_dispatch_order
     *
     * @mbggenerated
     */
    FactoryDispatchOrder selectByPrimaryKey(String serviceOrderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory_dispatch_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FactoryDispatchOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory_dispatch_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FactoryDispatchOrder record);
}