package com.cms.mapper.maoyi;

import java.util.List;

import com.cms.model.maoyi.OrderIncoming;

public interface OrderIncomingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_incoming
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_incoming
     *
     * @mbggenerated
     */
    int insert(OrderIncoming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_incoming
     *
     * @mbggenerated
     */
    int insertSelective(OrderIncoming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_incoming
     *
     * @mbggenerated
     */
    OrderIncoming selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_incoming
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderIncoming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_incoming
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderIncoming record);
    
     List<OrderIncoming> getGoodsIncoming(OrderIncoming orderIncoming);
    
}