package com.cms.model.maoyi;

import java.io.Serializable;

public class Customer implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.contact_ac
     *
     * @mbggenerated
     */
    private String contactAc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.contact_an
     *
     * @mbggenerated
     */
    private String contactAn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.contact_al
     *
     * @mbggenerated
     */
    private String contactAl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.contact_ad
     *
     * @mbggenerated
     */
    private String contactAd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.post_code
     *
     * @mbggenerated
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.name
     *
     * @return the value of customer.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.name
     *
     * @param name the value for customer.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.contact_ac
     *
     * @return the value of customer.contact_ac
     *
     * @mbggenerated
     */
    public String getContactAc() {
        return contactAc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.contact_ac
     *
     * @param contactAc the value for customer.contact_ac
     *
     * @mbggenerated
     */
    public void setContactAc(String contactAc) {
        this.contactAc = contactAc == null ? null : contactAc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.contact_an
     *
     * @return the value of customer.contact_an
     *
     * @mbggenerated
     */
    public String getContactAn() {
        return contactAn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.contact_an
     *
     * @param contactAn the value for customer.contact_an
     *
     * @mbggenerated
     */
    public void setContactAn(String contactAn) {
        this.contactAn = contactAn == null ? null : contactAn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.contact_al
     *
     * @return the value of customer.contact_al
     *
     * @mbggenerated
     */
    public String getContactAl() {
        return contactAl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.contact_al
     *
     * @param contactAl the value for customer.contact_al
     *
     * @mbggenerated
     */
    public void setContactAl(String contactAl) {
        this.contactAl = contactAl == null ? null : contactAl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.contact_ad
     *
     * @return the value of customer.contact_ad
     *
     * @mbggenerated
     */
    public String getContactAd() {
        return contactAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.contact_ad
     *
     * @param contactAd the value for customer.contact_ad
     *
     * @mbggenerated
     */
    public void setContactAd(String contactAd) {
        this.contactAd = contactAd == null ? null : contactAd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.post_code
     *
     * @return the value of customer.post_code
     *
     * @mbggenerated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.post_code
     *
     * @param postCode the value for customer.post_code
     *
     * @mbggenerated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone
     *
     * @return the value of customer.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone
     *
     * @param phone the value for customer.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}