package com.cms.model.maoyi;

import java.io.Serializable;

public class OrderIncoming implements Serializable{
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.supplierId
     *
     * @mbggenerated
     */
    private String supplierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.supplier_type
     *
     * @mbggenerated
     */
    private Integer supplierType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.supplier_name
     *
     * @mbggenerated
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.supplier_contact
     *
     * @mbggenerated
     */
    private String supplierContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.supplier_phone
     *
     * @mbggenerated
     */
    private String supplierPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.total
     *
     * @mbggenerated
     */
    private Long total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.created_time
     *
     * @mbggenerated
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.delivery_time
     *
     * @mbggenerated
     */
    private String deliveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.EntId
     *
     * @mbggenerated
     */
    private String entid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.CreatedByUId
     *
     * @mbggenerated
     */
    private String createdbyuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.CreatedByUser
     *
     * @mbggenerated
     */
    private String createdbyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.record_state
     *
     * @mbggenerated
     */
    private Integer recordState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.check_state
     *
     * @mbggenerated
     */
    private Integer checkState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.jinghuo_state
     *
     * @mbggenerated
     */
    private Integer jinghuoState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.fapiao_state
     *
     * @mbggenerated
     */
    private Integer fapiaoState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_incoming.jiaofu_state
     *
     * @mbggenerated
     */
    private Integer jiaofuState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.id
     *
     * @return the value of order_incoming.id
     *
     * @mbggenerated
     */
    
    private String productName;//商品名称
    
    private String intimeMin;
    private String intimeMax;
    private String endtimeMin;
    private String endtimeMax;
    public String getIntimeMin() {
		return intimeMin;
	}

	public void setIntimeMin(String intimeMin) {
		this.intimeMin = intimeMin;
	}

	public String getIntimeMax() {
		return intimeMax;
	}

	public void setIntimeMax(String intimeMax) {
		this.intimeMax = intimeMax;
	}

	public String getEndtimeMin() {
		return endtimeMin;
	}

	public void setEndtimeMin(String endtimeMin) {
		this.endtimeMin = endtimeMin;
	}

	public String getEndtimeMax() {
		return endtimeMax;
	}

	public void setEndtimeMax(String endtimeMax) {
		this.endtimeMax = endtimeMax;
	}

	
    public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.id
     *
     * @param id the value for order_incoming.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.supplierId
     *
     * @return the value of order_incoming.supplierId
     *
     * @mbggenerated
     */
    public String getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.supplierId
     *
     * @param supplierid the value for order_incoming.supplierId
     *
     * @mbggenerated
     */
    public void setSupplierid(String supplierid) {
        this.supplierid = supplierid == null ? null : supplierid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.supplier_type
     *
     * @return the value of order_incoming.supplier_type
     *
     * @mbggenerated
     */
    public Integer getSupplierType() {
        return supplierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.supplier_type
     *
     * @param supplierType the value for order_incoming.supplier_type
     *
     * @mbggenerated
     */
    public void setSupplierType(Integer supplierType) {
        this.supplierType = supplierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.supplier_name
     *
     * @return the value of order_incoming.supplier_name
     *
     * @mbggenerated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.supplier_name
     *
     * @param supplierName the value for order_incoming.supplier_name
     *
     * @mbggenerated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.supplier_contact
     *
     * @return the value of order_incoming.supplier_contact
     *
     * @mbggenerated
     */
    public String getSupplierContact() {
        return supplierContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.supplier_contact
     *
     * @param supplierContact the value for order_incoming.supplier_contact
     *
     * @mbggenerated
     */
    public void setSupplierContact(String supplierContact) {
        this.supplierContact = supplierContact == null ? null : supplierContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.supplier_phone
     *
     * @return the value of order_incoming.supplier_phone
     *
     * @mbggenerated
     */
    public String getSupplierPhone() {
        return supplierPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.supplier_phone
     *
     * @param supplierPhone the value for order_incoming.supplier_phone
     *
     * @mbggenerated
     */
    public void setSupplierPhone(String supplierPhone) {
        this.supplierPhone = supplierPhone == null ? null : supplierPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.count
     *
     * @return the value of order_incoming.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.count
     *
     * @param count the value for order_incoming.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.total
     *
     * @return the value of order_incoming.total
     *
     * @mbggenerated
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.total
     *
     * @param total the value for order_incoming.total
     *
     * @mbggenerated
     */
    public void setTotal(Long total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.created_time
     *
     * @return the value of order_incoming.created_time
     *
     * @mbggenerated
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.created_time
     *
     * @param createdTime the value for order_incoming.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.delivery_time
     *
     * @return the value of order_incoming.delivery_time
     *
     * @mbggenerated
     */
    public String getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.delivery_time
     *
     * @param deliveryTime the value for order_incoming.delivery_time
     *
     * @mbggenerated
     */
    public void setDeliveryTime(String deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.EntId
     *
     * @return the value of order_incoming.EntId
     *
     * @mbggenerated
     */
    public String getEntid() {
        return entid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.EntId
     *
     * @param entid the value for order_incoming.EntId
     *
     * @mbggenerated
     */
    public void setEntid(String entid) {
        this.entid = entid == null ? null : entid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.CreatedByUId
     *
     * @return the value of order_incoming.CreatedByUId
     *
     * @mbggenerated
     */
    public String getCreatedbyuid() {
        return createdbyuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.CreatedByUId
     *
     * @param createdbyuid the value for order_incoming.CreatedByUId
     *
     * @mbggenerated
     */
    public void setCreatedbyuid(String createdbyuid) {
        this.createdbyuid = createdbyuid == null ? null : createdbyuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.CreatedByUser
     *
     * @return the value of order_incoming.CreatedByUser
     *
     * @mbggenerated
     */
    public String getCreatedbyuser() {
        return createdbyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.CreatedByUser
     *
     * @param createdbyuser the value for order_incoming.CreatedByUser
     *
     * @mbggenerated
     */
    public void setCreatedbyuser(String createdbyuser) {
        this.createdbyuser = createdbyuser == null ? null : createdbyuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.record_state
     *
     * @return the value of order_incoming.record_state
     *
     * @mbggenerated
     */
    public Integer getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.record_state
     *
     * @param recordState the value for order_incoming.record_state
     *
     * @mbggenerated
     */
    public void setRecordState(Integer recordState) {
        this.recordState = recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.check_state
     *
     * @return the value of order_incoming.check_state
     *
     * @mbggenerated
     */
    public Integer getCheckState() {
        return checkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.check_state
     *
     * @param checkState the value for order_incoming.check_state
     *
     * @mbggenerated
     */
    public void setCheckState(Integer checkState) {
        this.checkState = checkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.jinghuo_state
     *
     * @return the value of order_incoming.jinghuo_state
     *
     * @mbggenerated
     */
    public Integer getJinghuoState() {
        return jinghuoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.jinghuo_state
     *
     * @param jinghuoState the value for order_incoming.jinghuo_state
     *
     * @mbggenerated
     */
    public void setJinghuoState(Integer jinghuoState) {
        this.jinghuoState = jinghuoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.fapiao_state
     *
     * @return the value of order_incoming.fapiao_state
     *
     * @mbggenerated
     */
    public Integer getFapiaoState() {
        return fapiaoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.fapiao_state
     *
     * @param fapiaoState the value for order_incoming.fapiao_state
     *
     * @mbggenerated
     */
    public void setFapiaoState(Integer fapiaoState) {
        this.fapiaoState = fapiaoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_incoming.jiaofu_state
     *
     * @return the value of order_incoming.jiaofu_state
     *
     * @mbggenerated
     */
    public Integer getJiaofuState() {
        return jiaofuState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_incoming.jiaofu_state
     *
     * @param jiaofuState the value for order_incoming.jiaofu_state
     *
     * @mbggenerated
     */
    public void setJiaofuState(Integer jiaofuState) {
        this.jiaofuState = jiaofuState;
    }

	@Override
	public String toString() {
		return "OrderIncoming [id=" + id + ", supplierid=" + supplierid + ", supplierType=" + supplierType
				+ ", supplierName=" + supplierName + ", supplierContact=" + supplierContact + ", supplierPhone="
				+ supplierPhone + ", count=" + count + ", total=" + total + ", createdTime=" + createdTime
				+ ", deliveryTime=" + deliveryTime + ", entid=" + entid + ", createdbyuid=" + createdbyuid
				+ ", createdbyuser=" + createdbyuser + ", recordState=" + recordState + ", checkState=" + checkState
				+ ", jinghuoState=" + jinghuoState + ", fapiaoState=" + fapiaoState + ", jiaofuState=" + jiaofuState
				+ ", productName=" + productName + ", intimeMin=" + intimeMin + ", intimeMax=" + intimeMax
				+ ", endtimeMin=" + endtimeMin + ", endtimeMax=" + endtimeMax + "]";
	}
    
}